[workspace]
members = [
	"crates/zoroswap",
	"crates/zoro_primitives",
	"crates/zoro_miden_client"
]
resolver = "2"

[workspace.dependencies]
alloy = { version = "1.0.23", features = ["full"] }

[patch.crates-io]
zoro_curve = { path = "../zoro-curve" }
