[[faucets]]
symbol = "BTC"
decimals = 8
max_supply = 1_000_000_000_000_000_000

[[faucets]]
symbol = "ETH"
decimals = 8
max_supply = 1_000_000_000_000_000_000

[[faucets]]
symbol = "USDC"
decimals = 8
max_supply = 1_000_000_000_000_000_000
